#!/bin/bash

source /usr/share/openldap/common

set -eux
CONFD="${BASE_CONFD}/init"

# Forbid anonymous access and update ACL for docker "mail"
changeAccess () {
	tmp=$(mktemp)
	replaceValues>"${tmp}" "${CONFD}/change_access.ldif" DC "${DC}"

	setValue SLAPD_LDAPS yes /etc/default/slapd
	setValue SLAPD_SERVICES "\"ldap:/// ldaps:/// ldapi:///\"" /etc/default/slapd

	ldapmodify ${LDAP_OPTS} -f "${tmp}"
}

configSSL() {
	tmp=$(mktemp)
	mkdir -p /ssl
	chown -R openldap /ssl/*  ||:
	chmod -R 700 /ssl/*       ||:

	replaceValues>"${tmp}" "${CONFD}/tls_config.ldif" LDAP_DOMAIN "ldap.${LDAP_DOMAIN}"

	ldapmodify -QY EXTERNAL -H ldapi:/// -f "${tmp}"
}

configMail () {
	tmpdir=$(mktemp -d)
	tmp=$(mktemp)

	cp /usr/share/doc/courier-authlib-ldap/authldap.schema /etc/ldap/schema
		
	FIRSTLINE=$(grep -n "^#.*mailhost" /etc/ldap/schema/authldap.schema  | cut -d ":" -f 1)
	NBLINES=$(cat /etc/ldap/schema/authldap.schema | wc -l)
	head -n $(($FIRSTLINE-1)) /etc/ldap/schema/authldap.schema > "${tmp}"
	cat /etc/ldap/schema/authldap.schema | head -n $(($FIRSTLINE+3)) | tail -n 4 | cut -d '#' -f 2 >> "${tmp}"
	tail -n $(($NBLINES-$FIRSTLINE-3)) /etc/ldap/schema/authldap.schema >> "${tmp}"
	cp "${tmp}" /etc/ldap/schema/authldap.schema

	slaptest -f "${CONFD}/schemaInclude.conf" -F "${tmpdir}"

	schemas="${tmpdir}/cn=config/cn=schema"
	cd "${schemas}"

	authldap=$(ls | grep authldap)

	tmp=$(mktemp)
	cat "${schemas}/${authldap}" | sed -re 's/(cn.+)\{[0-9]\}(.*)$/\1\2/g' | sed -re "s/cn=authldap/cn=authldap,cn=schema,cn=config/g" > "${tmp}"

	head -n $(($(cat "${schemas}/${authldap}"|wc -l)-7)) "${tmp}" > "$authldap"

	ldapadd ${LDAP_OPTS} -f "$schemas/$authldap"
}

configMemberof () {
	ldapadd ${LDAP_OPTS} -f "${CONFD}/memberof_config.ldif"
	ldapmodify ${LDAP_OPTS} -f "${CONFD}/refint1.ldif"
	ldapadd ${LDAP_OPTS} -f "${CONFD}/refint2.ldif"
}

configBase () {
	tmp=$(mktemp)
	replaceValues>"${tmp}" "${CONFD}/basic.ldif" DC "${DC}"
	ldapadd ${LDAP_OPTS_ADMIN} -f "${tmp}"
}

configPHPLDAPAdmin() {
	# Configure phpldapadmin
	sed -i "s/\(\$servers->setValue('server','name','\)\(.*\)\(');\)$/\1${LDAP_SERVERNAME}\3/g" /etc/phpldapadmin/config.php
	sed -i "s/\(\$servers->setValue('server','base',array('\)\(.*\)\('));\)$/\1${DC}\3/g" /etc/phpldapadmin/config.php
	sed -i "s/\(\$servers->setValue('login','bind_id','\)\(.*\)\(');\)$/\1cn=admin,${DC}\3/g" /etc/phpldapadmin/config.php
	sed -i "s/\(\$servers->setValue('login','bind_pass','\)\(.*\)\(');\)$/\1$(escape ${LDAP_PASSWORD})\3/g" /etc/phpldapadmin/config.php
	sed -i "s/\(\$servers->setValue('server','tls',\)\(.*\)\();\)$/\1true\3/g" /etc/phpldapadmin/config.php
}

# If slapd was already running by another mean than init.d
pkill slapd ||:

if ([ -z "$(ls -A /etc/ldap/slapd.d)" ] || [ -z "$(ls -A /var/lib/ldap)" ]); then
	status "configuring slapd for first run"

	cat <<EOF | debconf-set-selections
slapd slapd/password2 password ${LDAP_PASSWORD}
slapd slapd/password1 password ${LDAP_PASSWORD}
slapd slapd/internal/generated_adminpw password ${LDAP_PASSWORD}
slapd slapd/internal/adminpw password ${LDAP_PASSWORD}
slapd slapd/dump_database_destdir string /var/backups/slapd-VERSION
slapd slapd/domain string ${LDAP_DOMAIN}
slapd shared/organization string ${LDAP_ORGANISATION}
slapd slapd/backend string HDB
slapd slapd/purge_database boolean false
slapd slapd/move_old_database boolean false
slapd slapd/allow_ldap_v2 boolean false
slapd slapd/no_configuration boolean false
slapd slapd/dump_database select when needed
EOF

	dpkg-reconfigure -f noninteractive slapd

	/etc/init.d/slapd start

	changeAccess
	[ "${LDAP_SSL}" = "1" ] && configSSL
	configMail
	configMemberof
	configBase

	/etc/init.d/slapd stop
else
	status "found already-configured slapd"

	configPHPLDAPAdmin
	setValue SLAPD_LDAPS yes /etc/default/slapd
	setValue SLAPD_SERVICES "\"ldap:/// ldaps:/// ldapi:///\"" /etc/default/slapd
fi

status "starting slapd"
/etc/init.d/slapd start
